using Rusty.Serialization;
using Rusty.Serialization.Converters;
using Rusty.Serialization.Test;
using Rusty.Serialization.Testing;
using System;
using System.Collections;

//UnitTests.RunParserTests(true);
//UnitTests.RunSerializeTests();
Context context = new();
context.AddConverter<bool, BoolConverter>();
context.AddConverter<int, IntConverter>();
context.AddConverter<float, FloatConverter>();
context.AddConverter<char, CharConverter>();
context.AddConverter<string, StringConverter>();
context.AddConverter<byte[], ByteArrayConverter>();
context.AddConverter(typeof(System.ValueTuple<>), typeof(TupleConverter<>));
Console.WriteLine(context.Serialize(new byte[] { 1, 2, 3 }));
Console.WriteLine(context.Serialize(new int[] { 1, 2, 3 }));
Console.WriteLine(context.Serialize(new int[][] { [1, 2, 3], [], [4, 5, 6] }));
Console.WriteLine(context.Serialize((5, 'C')));
Console.WriteLine(context.Serialize(System.ConsoleKey.P));
return;
